// src/components/voucher/VoucherStorePerformance.jsx
import React from "react";

const formatCurrency = (value) =>
  `₹${Number(value ?? 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

export default function VoucherStorePerformance({ storePerformance }) {
  const stores = storePerformance || [];
  const maxRevenue = Math.max(...stores.map((s) => s.revenue), 1);

  return (
    <section className="rounded-xl border border-gray-200 bg-white p-5">
      <h2 className="text-sm font-semibold text-gray-900">Store Performance Revenue</h2>
      <p className="mt-1 text-xs text-gray-500">
        Store-wise Revenue provides a detailed breakdown of earnings generated by each
        store or outlet.
      </p>

      <div className="mt-4 space-y-4">
        {stores.length === 0 ? (
          <p className="text-xs text-gray-400">No store data available yet.</p>
        ) : (
          stores.map((store) => (
            <div key={store.storeName}>
              <div className="mb-1 flex items-center justify-between text-xs">
                <span className="font-medium text-gray-700">{store.storeName}</span>
                <span className="text-gray-500">{formatCurrency(store.revenue)}</span>
              </div>
              <div className="h-2 w-full rounded-full bg-gray-100">
                <div
                  className="h-2 rounded-full bg-indigo-600"
                  style={{ width: `${(store.revenue / maxRevenue) * 100}%` }}
                />
              </div>
            </div>
          ))
        )}
      </div>
    </section>
  );
}